- Ingredient: Wood
  Source: Beech
- Ingredient: Wood
  Source: Fir
- Ingredient: Wood
  Source: Pine
- Ingredient: Wood
  Source: Tree
- Ingredient: Fine Wood
  Source: Birch
- Ingredient: Wood
  Source: Birch
- Ingredient: Wood
  Source: Oak
- Ingredient: Fine Wood
  Source: Oak
- Ingredient: Core Wood
  Source: Pine
- Ingredient: Copper Ore
  Source: Copper Deposit
- Ingredient: Tin Ore
  Source: Tin Deposit
- Ingredient: Bone Fragments
  Source: Skeletons
- Ingredient: Bronze
  Source: Crafted
- Ingredient: Copper
  Source: Crafted
- Ingredient: Tin
  Source: Crafted
